version: "3.7"
services:
  tarefa1_8080:
    image: tarefa1
    container_name: tarefa1_8080
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - tarefa1network
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/basics?allowPublicKeyRetrieval=true    
    depends_on:
      - mysqldb
  tarefa1_8081:
    image: tarefa1
    container_name: tarefa1_8081
    build: .
    restart: always
    ports:
      - 8081:8081
    networks:
      - tarefa1network
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/basics?allowPublicKeyRetrieval=true
    depends_on:
      - mysqldb
  tarefa1_8082:
    image: tarefa1
    container_name: tarefa1_8082
    build: .
    restart: always
    ports:
      - 8082:8082
    networks:
      - tarefa1network
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/basics?allowPublicKeyRetrieval=true
    depends_on:
      - mysqldb



  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    networks:
      - tarefa1network
    environment:
      MYSQL_DATABASE: booksdatabase
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
networks:
  tarefa1network:
